name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment (e.g., 'dev')
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to use the latest version
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure the requirements file is named correctly

      - name: Install Node.js
        uses: actions/setup-node@v3  # Install Node.js to ensure compatibility with Vercel CLI
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Set this in GitHub Secrets
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Set this in GitHub Secrets
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJ_ID }}  # Set this in GitHub Secrets
        run: |
          npm install -g vercel  # Install Vercel CLI
          vercel --token $VERCEL_TOKEN --prod --confirm  # Deploy with Vercel CLI
