name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt  # Adjust the requirements file name if needed

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Set this in GitHub Secrets
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Set this in GitHub Secrets
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Set this in GitHub Secrets
      run: |
        npm install -g vercel  # Install Vercel CLI
        vercel --token $VERCEL_TOKEN --org-id $VERCEL_ORG_ID --project-id $VERCEL_PROJECT_ID --prod
